sonar.projectKey=trading-bot
sonar.projectName=Trading Bot
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8

# Python specific
sonar.language=py

# Optional (if you add coverage later)
sonar.python.coverage.reportPaths=coverage.xml